baseURL = 'https://werdado.github.io/plan-ogolny-gdansk/'
defaultContentLanguage = 'pl'
languageCode = 'pl_PL'

title = 'Wnioski do Planu Ogólnego / Gdańsk'

[markup]
    [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ['html', 'rss', 'json']
  section = ['html', 'rss', 'json']
  taxonomy = ['html']

[params]
    index = "Rejestr wniosków"
    avatarImg = "/images/werdado_sign.png"