# baseURL = '${site.getBaseUrl()}'
baseURL = 'http://example.com'
defaultContentLanguage = 'pl'
languageCode = 'pl_PL'

title = '${site.getTitle()}'

[markup]
    [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ['html', 'rss', 'json']
  section = ['html', 'rss', 'json']
  taxonomy = ['html']

[params]
    index = "Rejestr"
    about = "Czym jest werdado?"
    avatarImg = "/images/werdado_sign.png"